spring.application.name=PersonalDashboard

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./database/personal_dashboard_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 Console (For Testing)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
